  server:
    port: 8090
  spring:
    application:
      name: gateway-server
    cloud:
      gateway:
        discovery:
          locator:
            enabled: true
            lower-case-service-id: true # Ensures service names are lowercase in routes
        routes:
        - id: movie-catalog-service
          uri: lb://movie-catalog-service
          predicates:
          - Path=/catalog/**
          filters:
          - StripPrefix=0
        - id: movie-info-service
          uri: lb://movie-info-service
          predicates:
          - Path=/movies/**
          filters:
          - StripPrefix=0
        - id: rating-data-service
          uri: lb://rating-data-service
          predicates:
          - Path=/ratings/**
          filters:
          - StripPrefix=0
  eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:8762/eureka/
