spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      routes:
      - id: nameRoot
        uri: http://localhost:8081
        predicates:
        - Path=/catalog/**
        filters:
        - StripPrefix=0
